FROM python:[[ python_version ]]-slim as build-image
ENV PYTHONUNBUFFERED 1

RUN mkdir /[[package_name]]

COPY build/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

WORKDIR /[[package_name]]
# EXPOSE <port>
COPY [[package_name]] /[[package_name]]

ENTRYPOINT [ "python", "app.py" ]
