FROM python:[[ python_version ]]-slim

RUN mkdir /[[package_name]]


COPY build/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt


# RUN pip3 install micropipenv[toml]
# COPY pyproject.toml /pyproject.toml
# COPY poetry.lock /poetry.lock
# RUN micropipenv install

WORKDIR /[[package_name]]
# EXPOSE <port>
COPY [[package_name]] /[[package_name]]
